#if !defined(BR_STRLC)
#  define BR_STRLC(STR) { .str = STR, .len = sizeof(STR) - 1 }
#endif
const br_strv_t br_license[] = {
  BR_STRLC("The MIT License (MIT)"),
  BR_STRLC("Copyright © 2025 Branimir Ričko [branc116]"),
  BR_STRLC(""),
  BR_STRLC("Permission is hereby granted, free of charge, to any person  obtaining a copy of"),
  BR_STRLC("this software and associated  documentation files (the   “Software”), to deal in"),
  BR_STRLC("the Software without  restriction,  including without  limitation  the rights to"),
  BR_STRLC("use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of"),
  BR_STRLC("the Software,  and to permit persons to whom the Software is furnished to do so,"),
  BR_STRLC("subject to the following conditions:"),
  BR_STRLC(""),
  BR_STRLC("The above  copyright notice and this  permission notice shall be included in all"),
  BR_STRLC("copies or substantial portions of the Software."),
  BR_STRLC(""),
  BR_STRLC("THE SOFTWARE IS PROVIDED   “AS IS”,   WITHOUT WARRANTY OF ANY KIND,   EXPRESS OR"),
  BR_STRLC("IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS"),
  BR_STRLC("FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.   IN NO EVENT SHALL THE AUTHORS OR"),
  BR_STRLC("COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,  DAMAGES OR OTHER LIABILITY,  WHETHER"),
  BR_STRLC("IN  AN  ACTION  OF CONTRACT,   TORT OR OTHERWISE,   ARISING FROM,   OUT OF OR IN"),
  BR_STRLC("CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE."),
  BR_STRLC("================================stb_image======================================"),
  BR_STRLC("================================stb_image_write================================"),
  BR_STRLC("================================stb_rect_pack=================================="),
  BR_STRLC("================================stb_truetype==================================="),
  BR_STRLC("================================stb_ds========================================="),
  BR_STRLC(" ALTERNATIVE A - MIT License"),
  BR_STRLC(" Copyright (c) 2017 Sean Barrett"),
  BR_STRLC(" Permission is hereby granted, free of charge, to any person obtaining a copy of"),
  BR_STRLC(" this software and associated documentation files (the \"Software\"), to deal in"),
  BR_STRLC(" the Software without restriction, including without limitation the rights to"),
  BR_STRLC(" use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies"),
  BR_STRLC(" of the Software, and to permit persons to whom the Software is furnished to do"),
  BR_STRLC(" so, subject to the following conditions:"),
  BR_STRLC(" The above copyright notice and this permission notice shall be included in all"),
  BR_STRLC(" copies or substantial portions of the Software."),
  BR_STRLC(" THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR"),
  BR_STRLC(" IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,"),
  BR_STRLC(" FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE"),
  BR_STRLC(" AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER"),
  BR_STRLC(" LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,"),
  BR_STRLC(" OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE"),
  BR_STRLC(" SOFTWARE."),
  BR_STRLC("================================stb_*========================================="),
  BR_STRLC("===============================TRACY============================================"),
  BR_STRLC(""),
  BR_STRLC(" Tracy Profiler (https://github.com/wolfpld/tracy) is licensed under the"),
  BR_STRLC(" 3-clause BSD license."),
  BR_STRLC(""),
  BR_STRLC(" Copyright (c) 2017-2023, Bartosz Taudul <wolf@nereid.pl>"),
  BR_STRLC(" All rights reserved."),
  BR_STRLC(""),
  BR_STRLC(" Redistribution and use in source and binary forms, with or without"),
  BR_STRLC(" modification, are permitted provided that the following conditions are met:"),
  BR_STRLC("     * Redistributions of source code must retain the above copyright"),
  BR_STRLC("       notice, this list of conditions and the following disclaimer."),
  BR_STRLC("     * Redistributions in binary form must reproduce the above copyright"),
  BR_STRLC("       notice, this list of conditions and the following disclaimer in the"),
  BR_STRLC("       documentation and/or other materials provided with the distribution."),
  BR_STRLC("     * Neither the name of the <organization> nor the"),
  BR_STRLC("       names of its contributors may be used to endorse or promote products"),
  BR_STRLC("       derived from this software without specific prior written permission."),
  BR_STRLC(""),
  BR_STRLC(" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS \"AS IS\" AND"),
  BR_STRLC(" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED"),
  BR_STRLC(" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE"),
  BR_STRLC(" DISCLAIMED. IN NO EVENT SHALL <COPYRIGHT HOLDER> BE LIABLE FOR ANY"),
  BR_STRLC(" DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES"),
  BR_STRLC(" (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;"),
  BR_STRLC(" LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND"),
  BR_STRLC(" ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT"),
  BR_STRLC(" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS"),
  BR_STRLC(" SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE."),
  BR_STRLC("===============================TRACY==========================================="),
  BR_STRLC("===================================nob======================================"),
  BR_STRLC(" ALTERNATIVE B - Public Domain (www.unlicense.org)"),
  BR_STRLC(" This is free and unencumbered software released into the public domain."),
  BR_STRLC(" Anyone is free to copy, modify, publish, use, compile, sell, or distribute this"),
  BR_STRLC(" software, either in source code form or as a compiled binary, for any purpose,"),
  BR_STRLC(" commercial or non-commercial, and by any means."),
  BR_STRLC(" In jurisdictions that recognize copyright laws, the author or authors of this"),
  BR_STRLC(" software dedicate any and all copyright interest in the software to the public"),
  BR_STRLC(" domain. We make this dedication for the benefit of the public at large and to"),
  BR_STRLC(" the detriment of our heirs and successors. We intend this dedication to be an"),
  BR_STRLC(" overt act of relinquishment in perpetuity of all present and future rights to"),
  BR_STRLC(" this software under copyright law."),
  BR_STRLC(" THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR"),
  BR_STRLC(" IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,"),
  BR_STRLC(" FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE"),
  BR_STRLC(" AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN"),
  BR_STRLC(" ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION"),
  BR_STRLC(" WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE."),
  BR_STRLC("===================================nob======================================"),
  BR_STRLC("")
};
int br_license_lines = 92;

