#if !defined(BR_STRLC)
#  define BR_STRLC(STR) { .str = STR, .len = sizeof(STR) - 1 }
#endif
const br_strv_t br_license[] = {
  BR_STRLC("The MIT License (MIT)"),
  BR_STRLC("Copyright © 2025 Branimir Ričko [branc116]"),
  BR_STRLC(""),
  BR_STRLC("Permission is hereby granted, free of charge, to any person  obtaining a copy of"),
  BR_STRLC("this software and associated  documentation files (the   “Software”), to deal in"),
  BR_STRLC("the Software without  restriction,  including without  limitation  the rights to"),
  BR_STRLC("use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of"),
  BR_STRLC("the Software,  and to permit persons to whom the Software is furnished to do so,"),
  BR_STRLC("subject to the following conditions:"),
  BR_STRLC(""),
  BR_STRLC("The above  copyright notice and this  permission notice shall be included in all"),
  BR_STRLC("copies or substantial portions of the Software."),
  BR_STRLC(""),
  BR_STRLC("THE SOFTWARE IS PROVIDED   “AS IS”,   WITHOUT WARRANTY OF ANY KIND,   EXPRESS OR"),
  BR_STRLC("IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS"),
  BR_STRLC("FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.   IN NO EVENT SHALL THE AUTHORS OR"),
  BR_STRLC("COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,  DAMAGES OR OTHER LIABILITY,  WHETHER"),
  BR_STRLC("IN  AN  ACTION  OF CONTRACT,   TORT OR OTHERWISE,   ARISING FROM,   OUT OF OR IN"),
  BR_STRLC("CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE."),
  BR_STRLC("==================================RAYLIB========================================"),
  BR_STRLC("== Branimir =="),
  BR_STRLC("Even tho I have removed raylib from this project. Some of the code is inspired by/copyed from"),
  BR_STRLC("raylib. So if you find a line of code that Ramon created, it's thanks to him that this works."),
  BR_STRLC("And if you find a line of code that Ramon created and it's because of that line that brplot doesn't work,"),
  BR_STRLC("you should blame me."),
  BR_STRLC("== End of Branimir =="),
  BR_STRLC(" Copyright (c) 2013-2023 Ramon Santamaria (@raysan5)"),
  BR_STRLC(""),
  BR_STRLC(" This software is provided \"as-is\", without any express or implied warranty. In no event"),
  BR_STRLC(" will the authors be held liable for any damages arising from the use of this software."),
  BR_STRLC(""),
  BR_STRLC(" Permission is granted to anyone to use this software for any purpose, including commercial"),
  BR_STRLC(" applications, and to alter it and redistribute it freely, subject to the following restrictions:"),
  BR_STRLC(""),
  BR_STRLC("   1. The origin of this software must not be misrepresented; you must not claim that you"),
  BR_STRLC("   wrote the original software. If you use this software in a product, an acknowledgment"),
  BR_STRLC("   in the product documentation would be appreciated but is not required."),
  BR_STRLC(""),
  BR_STRLC("   2. Altered source versions must be plainly marked as such, and must not be misrepresented"),
  BR_STRLC("   as being the original software."),
  BR_STRLC(""),
  BR_STRLC("   3. This notice may not be removed or altered from any source distribution."),
  BR_STRLC("=================================RAYLIB========================================="),
  BR_STRLC("=================================IMGUI=========================================="),
  BR_STRLC("== Branimir =="),
  BR_STRLC("Even tho I have removed imgui from this project. Some of the code is inspired by/copyed from"),
  BR_STRLC("imgui. So if you find a line of code that Omar created, it's thanks to him that this works."),
  BR_STRLC("And if you find a line of code that Omar created and it's because of that line that brplot doesn't work,"),
  BR_STRLC("you should blame me."),
  BR_STRLC("== End of Branimir =="),
  BR_STRLC(" The MIT License (MIT)"),
  BR_STRLC(""),
  BR_STRLC(" Copyright (c) 2014-2024 Omar Cornut"),
  BR_STRLC(""),
  BR_STRLC(" Permission is hereby granted, free of charge, to any person obtaining a copy"),
  BR_STRLC(" of this software and associated documentation files (the \"Software\"), to deal"),
  BR_STRLC(" in the Software without restriction, including without limitation the rights"),
  BR_STRLC(" to use, copy, modify, merge, publish, distribute, sublicense, and/or sell"),
  BR_STRLC(" copies of the Software, and to permit persons to whom the Software is"),
  BR_STRLC(" furnished to do so, subject to the following conditions:"),
  BR_STRLC(""),
  BR_STRLC(" The above copyright notice and this permission notice shall be included in all"),
  BR_STRLC(" copies or substantial portions of the Software."),
  BR_STRLC(""),
  BR_STRLC(" THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR"),
  BR_STRLC(" IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,"),
  BR_STRLC(" FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE"),
  BR_STRLC(" AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER"),
  BR_STRLC(" LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,"),
  BR_STRLC(" OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE"),
  BR_STRLC(" SOFTWARE."),
  BR_STRLC("=================================IMGUI=========================================="),
  BR_STRLC("================================GLFW============================================"),
  BR_STRLC(""),
  BR_STRLC(" Copyright (c) 2002-2006 Marcus Geelnard"),
  BR_STRLC(""),
  BR_STRLC(" Copyright (c) 2006-2019 Camilla Löwy"),
  BR_STRLC(""),
  BR_STRLC(" This software is provided 'as-is', without any express or implied"),
  BR_STRLC(" warranty. In no event will the authors be held liable for any damages"),
  BR_STRLC(" arising from the use of this software."),
  BR_STRLC(""),
  BR_STRLC(" Permission is granted to anyone to use this software for any purpose,"),
  BR_STRLC(" including commercial applications, and to alter it and redistribute it"),
  BR_STRLC(" freely, subject to the following restrictions:"),
  BR_STRLC(""),
  BR_STRLC(" 1. The origin of this software must not be misrepresented; you must not"),
  BR_STRLC("    claim that you wrote the original software. If you use this software"),
  BR_STRLC("    in a product, an acknowledgment in the product documentation would"),
  BR_STRLC("    be appreciated but is not required."),
  BR_STRLC(""),
  BR_STRLC(" 2. Altered source versions must be plainly marked as such, and must not"),
  BR_STRLC("    be misrepresented as being the original software."),
  BR_STRLC(""),
  BR_STRLC(" 3. This notice may not be removed or altered from any source"),
  BR_STRLC("    distribution."),
  BR_STRLC(""),
  BR_STRLC("===============================GLFW============================================="),
  BR_STRLC("===============================TRACY============================================"),
  BR_STRLC(""),
  BR_STRLC(" Tracy Profiler (https://github.com/wolfpld/tracy) is licensed under the"),
  BR_STRLC(" 3-clause BSD license."),
  BR_STRLC(""),
  BR_STRLC(" Copyright (c) 2017-2023, Bartosz Taudul <wolf@nereid.pl>"),
  BR_STRLC(" All rights reserved."),
  BR_STRLC(""),
  BR_STRLC(" Redistribution and use in source and binary forms, with or without"),
  BR_STRLC(" modification, are permitted provided that the following conditions are met:"),
  BR_STRLC("     * Redistributions of source code must retain the above copyright"),
  BR_STRLC("       notice, this list of conditions and the following disclaimer."),
  BR_STRLC("     * Redistributions in binary form must reproduce the above copyright"),
  BR_STRLC("       notice, this list of conditions and the following disclaimer in the"),
  BR_STRLC("       documentation and/or other materials provided with the distribution."),
  BR_STRLC("     * Neither the name of the <organization> nor the"),
  BR_STRLC("       names of its contributors may be used to endorse or promote products"),
  BR_STRLC("       derived from this software without specific prior written permission."),
  BR_STRLC(""),
  BR_STRLC(" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS \"AS IS\" AND"),
  BR_STRLC(" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED"),
  BR_STRLC(" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE"),
  BR_STRLC(" DISCLAIMED. IN NO EVENT SHALL <COPYRIGHT HOLDER> BE LIABLE FOR ANY"),
  BR_STRLC(" DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES"),
  BR_STRLC(" (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;"),
  BR_STRLC(" LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND"),
  BR_STRLC(" ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT"),
  BR_STRLC(" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS"),
  BR_STRLC(" SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE."),
  BR_STRLC("===============================TRACY==========================================="),
  BR_STRLC("================================stb_image======================================"),
  BR_STRLC(" ------------------------------------------------------------------------------"),
  BR_STRLC(" This software is available under 2 licenses -- choose whichever you prefer."),
  BR_STRLC(" ------------------------------------------------------------------------------"),
  BR_STRLC(" ALTERNATIVE A - MIT License"),
  BR_STRLC(" Copyright (c) 2017 Sean Barrett"),
  BR_STRLC(" Permission is hereby granted, free of charge, to any person obtaining a copy of"),
  BR_STRLC(" this software and associated documentation files (the \"Software\"), to deal in"),
  BR_STRLC(" the Software without restriction, including without limitation the rights to"),
  BR_STRLC(" use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies"),
  BR_STRLC(" of the Software, and to permit persons to whom the Software is furnished to do"),
  BR_STRLC(" so, subject to the following conditions:"),
  BR_STRLC(" The above copyright notice and this permission notice shall be included in all"),
  BR_STRLC(" copies or substantial portions of the Software."),
  BR_STRLC(" THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR"),
  BR_STRLC(" IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,"),
  BR_STRLC(" FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE"),
  BR_STRLC(" AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER"),
  BR_STRLC(" LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,"),
  BR_STRLC(" OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE"),
  BR_STRLC(" SOFTWARE."),
  BR_STRLC(" ------------------------------------------------------------------------------"),
  BR_STRLC(" ALTERNATIVE B - Public Domain (www.unlicense.org)"),
  BR_STRLC(" This is free and unencumbered software released into the public domain."),
  BR_STRLC(" Anyone is free to copy, modify, publish, use, compile, sell, or distribute this"),
  BR_STRLC(" software, either in source code form or as a compiled binary, for any purpose,"),
  BR_STRLC(" commercial or non-commercial, and by any means."),
  BR_STRLC(" In jurisdictions that recognize copyright laws, the author or authors of this"),
  BR_STRLC(" software dedicate any and all copyright interest in the software to the public"),
  BR_STRLC(" domain. We make this dedication for the benefit of the public at large and to"),
  BR_STRLC(" the detriment of our heirs and successors. We intend this dedication to be an"),
  BR_STRLC(" overt act of relinquishment in perpetuity of all present and future rights to"),
  BR_STRLC(" this software under copyright law."),
  BR_STRLC(" THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR"),
  BR_STRLC(" IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,"),
  BR_STRLC(" FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE"),
  BR_STRLC(" AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN"),
  BR_STRLC(" ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION"),
  BR_STRLC(" WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE."),
  BR_STRLC(" ------------------------------------------------------------------------------"),
  BR_STRLC("================================stb_image======================================"),
  BR_STRLC("===================================stb_image_write============================="),
  BR_STRLC(" ------------------------------------------------------------------------------"),
  BR_STRLC(" This software is available under 2 licenses -- choose whichever you prefer."),
  BR_STRLC(" ------------------------------------------------------------------------------"),
  BR_STRLC(" ALTERNATIVE A - MIT License"),
  BR_STRLC(" Copyright (c) 2017 Sean Barrett"),
  BR_STRLC(" Permission is hereby granted, free of charge, to any person obtaining a copy of"),
  BR_STRLC(" this software and associated documentation files (the \"Software\"), to deal in"),
  BR_STRLC(" the Software without restriction, including without limitation the rights to"),
  BR_STRLC(" use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies"),
  BR_STRLC(" of the Software, and to permit persons to whom the Software is furnished to do"),
  BR_STRLC(" so, subject to the following conditions:"),
  BR_STRLC(" The above copyright notice and this permission notice shall be included in all"),
  BR_STRLC(" copies or substantial portions of the Software."),
  BR_STRLC(" THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR"),
  BR_STRLC(" IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,"),
  BR_STRLC(" FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE"),
  BR_STRLC(" AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER"),
  BR_STRLC(" LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,"),
  BR_STRLC(" OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE"),
  BR_STRLC(" SOFTWARE."),
  BR_STRLC(" ------------------------------------------------------------------------------"),
  BR_STRLC(" ALTERNATIVE B - Public Domain (www.unlicense.org)"),
  BR_STRLC(" This is free and unencumbered software released into the public domain."),
  BR_STRLC(" Anyone is free to copy, modify, publish, use, compile, sell, or distribute this"),
  BR_STRLC(" software, either in source code form or as a compiled binary, for any purpose,"),
  BR_STRLC(" commercial or non-commercial, and by any means."),
  BR_STRLC(" In jurisdictions that recognize copyright laws, the author or authors of this"),
  BR_STRLC(" software dedicate any and all copyright interest in the software to the public"),
  BR_STRLC(" domain. We make this dedication for the benefit of the public at large and to"),
  BR_STRLC(" the detriment of our heirs and successors. We intend this dedication to be an"),
  BR_STRLC(" overt act of relinquishment in perpetuity of all present and future rights to"),
  BR_STRLC(" this software under copyright law."),
  BR_STRLC(" THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR"),
  BR_STRLC(" IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,"),
  BR_STRLC(" FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE"),
  BR_STRLC(" AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN"),
  BR_STRLC(" ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION"),
  BR_STRLC(" WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE."),
  BR_STRLC(" ------------------------------------------------------------------------------"),
  BR_STRLC("===================================stb_image_write============================="),
  BR_STRLC("===================================stb_rect_pack==============================="),
  BR_STRLC(" ------------------------------------------------------------------------------"),
  BR_STRLC(" This software is available under 2 licenses -- choose whichever you prefer."),
  BR_STRLC(" ------------------------------------------------------------------------------"),
  BR_STRLC(" ALTERNATIVE A - MIT License"),
  BR_STRLC(" Copyright (c) 2017 Sean Barrett"),
  BR_STRLC(" Permission is hereby granted, free of charge, to any person obtaining a copy of"),
  BR_STRLC(" this software and associated documentation files (the \"Software\"), to deal in"),
  BR_STRLC(" the Software without restriction, including without limitation the rights to"),
  BR_STRLC(" use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies"),
  BR_STRLC(" of the Software, and to permit persons to whom the Software is furnished to do"),
  BR_STRLC(" so, subject to the following conditions:"),
  BR_STRLC(" The above copyright notice and this permission notice shall be included in all"),
  BR_STRLC(" copies or substantial portions of the Software."),
  BR_STRLC(" THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR"),
  BR_STRLC(" IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,"),
  BR_STRLC(" FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE"),
  BR_STRLC(" AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER"),
  BR_STRLC(" LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,"),
  BR_STRLC(" OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE"),
  BR_STRLC(" SOFTWARE."),
  BR_STRLC(" ------------------------------------------------------------------------------"),
  BR_STRLC(" ALTERNATIVE B - Public Domain (www.unlicense.org)"),
  BR_STRLC(" This is free and unencumbered software released into the public domain."),
  BR_STRLC(" Anyone is free to copy, modify, publish, use, compile, sell, or distribute this"),
  BR_STRLC(" software, either in source code form or as a compiled binary, for any purpose,"),
  BR_STRLC(" commercial or non-commercial, and by any means."),
  BR_STRLC(" In jurisdictions that recognize copyright laws, the author or authors of this"),
  BR_STRLC(" software dedicate any and all copyright interest in the software to the public"),
  BR_STRLC(" domain. We make this dedication for the benefit of the public at large and to"),
  BR_STRLC(" the detriment of our heirs and successors. We intend this dedication to be an"),
  BR_STRLC(" overt act of relinquishment in perpetuity of all present and future rights to"),
  BR_STRLC(" this software under copyright law."),
  BR_STRLC(" THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR"),
  BR_STRLC(" IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,"),
  BR_STRLC(" FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE"),
  BR_STRLC(" AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN"),
  BR_STRLC(" ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION"),
  BR_STRLC(" WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE."),
  BR_STRLC(" ------------------------------------------------------------------------------"),
  BR_STRLC("===================================stb_rect_pack=============================="),
  BR_STRLC("===================================stb_truetype==============================="),
  BR_STRLC(" ------------------------------------------------------------------------------"),
  BR_STRLC(" This software is available under 2 licenses -- choose whichever you prefer."),
  BR_STRLC(" ------------------------------------------------------------------------------"),
  BR_STRLC(" ALTERNATIVE A - MIT License"),
  BR_STRLC(" Copyright (c) 2017 Sean Barrett"),
  BR_STRLC(" Permission is hereby granted, free of charge, to any person obtaining a copy of"),
  BR_STRLC(" this software and associated documentation files (the \"Software\"), to deal in"),
  BR_STRLC(" the Software without restriction, including without limitation the rights to"),
  BR_STRLC(" use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies"),
  BR_STRLC(" of the Software, and to permit persons to whom the Software is furnished to do"),
  BR_STRLC(" so, subject to the following conditions:"),
  BR_STRLC(" The above copyright notice and this permission notice shall be included in all"),
  BR_STRLC(" copies or substantial portions of the Software."),
  BR_STRLC(" THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR"),
  BR_STRLC(" IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,"),
  BR_STRLC(" FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE"),
  BR_STRLC(" AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER"),
  BR_STRLC(" LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,"),
  BR_STRLC(" OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE"),
  BR_STRLC(" SOFTWARE."),
  BR_STRLC(" ------------------------------------------------------------------------------"),
  BR_STRLC(" ALTERNATIVE B - Public Domain (www.unlicense.org)"),
  BR_STRLC(" This is free and unencumbered software released into the public domain."),
  BR_STRLC(" Anyone is free to copy, modify, publish, use, compile, sell, or distribute this"),
  BR_STRLC(" software, either in source code form or as a compiled binary, for any purpose,"),
  BR_STRLC(" commercial or non-commercial, and by any means."),
  BR_STRLC(" In jurisdictions that recognize copyright laws, the author or authors of this"),
  BR_STRLC(" software dedicate any and all copyright interest in the software to the public"),
  BR_STRLC(" domain. We make this dedication for the benefit of the public at large and to"),
  BR_STRLC(" the detriment of our heirs and successors. We intend this dedication to be an"),
  BR_STRLC(" overt act of relinquishment in perpetuity of all present and future rights to"),
  BR_STRLC(" this software under copyright law."),
  BR_STRLC(" THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR"),
  BR_STRLC(" IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,"),
  BR_STRLC(" FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE"),
  BR_STRLC(" AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN"),
  BR_STRLC(" ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION"),
  BR_STRLC(" WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE."),
  BR_STRLC(" ------------------------------------------------------------------------------"),
  BR_STRLC("===================================stb_truetype================================"),
  BR_STRLC("===================================stb_ds======================================"),
  BR_STRLC(" ------------------------------------------------------------------------------"),
  BR_STRLC(" This software is available under 2 licenses -- choose whichever you prefer."),
  BR_STRLC(" ------------------------------------------------------------------------------"),
  BR_STRLC(" ALTERNATIVE A - MIT License"),
  BR_STRLC(" Copyright (c) 2019 Sean Barrett"),
  BR_STRLC(" Permission is hereby granted, free of charge, to any person obtaining a copy of"),
  BR_STRLC(" this software and associated documentation files (the \"Software\"), to deal in"),
  BR_STRLC(" the Software without restriction, including without limitation the rights to"),
  BR_STRLC(" use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies"),
  BR_STRLC(" of the Software, and to permit persons to whom the Software is furnished to do"),
  BR_STRLC(" so, subject to the following conditions:"),
  BR_STRLC(" The above copyright notice and this permission notice shall be included in all"),
  BR_STRLC(" copies or substantial portions of the Software."),
  BR_STRLC(" THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR"),
  BR_STRLC(" IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,"),
  BR_STRLC(" FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE"),
  BR_STRLC(" AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER"),
  BR_STRLC(" LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,"),
  BR_STRLC(" OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE"),
  BR_STRLC(" SOFTWARE."),
  BR_STRLC(" ------------------------------------------------------------------------------"),
  BR_STRLC(" ALTERNATIVE B - Public Domain (www.unlicense.org)"),
  BR_STRLC(" This is free and unencumbered software released into the public domain."),
  BR_STRLC(" Anyone is free to copy, modify, publish, use, compile, sell, or distribute this"),
  BR_STRLC(" software, either in source code form or as a compiled binary, for any purpose,"),
  BR_STRLC(" commercial or non-commercial, and by any means."),
  BR_STRLC(" In jurisdictions that recognize copyright laws, the author or authors of this"),
  BR_STRLC(" software dedicate any and all copyright interest in the software to the public"),
  BR_STRLC(" domain. We make this dedication for the benefit of the public at large and to"),
  BR_STRLC(" the detriment of our heirs and successors. We intend this dedication to be an"),
  BR_STRLC(" overt act of relinquishment in perpetuity of all present and future rights to"),
  BR_STRLC(" this software under copyright law."),
  BR_STRLC(" THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR"),
  BR_STRLC(" IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,"),
  BR_STRLC(" FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE"),
  BR_STRLC(" AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN"),
  BR_STRLC(" ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION"),
  BR_STRLC(" WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE."),
  BR_STRLC(" ------------------------------------------------------------------------------"),
  BR_STRLC("===================================stb_ds======================================"),
  BR_STRLC("===================================quick_benchmark============================="),
  BR_STRLC(""),
  BR_STRLC(" The MIT License"),
  BR_STRLC(""),
  BR_STRLC(" Copyright 2018 Andrea Vouk."),
  BR_STRLC(""),
  BR_STRLC(" Permission is hereby granted, free of charge, to any person obtaining a copy"),
  BR_STRLC(" of this software and associated documentation files (the \"Software\"), to deal"),
  BR_STRLC(" in the Software without restriction, including without limitation the rights"),
  BR_STRLC(" to use, copy, modify, merge, publish, distribute, sublicense, and/or sell"),
  BR_STRLC(" copies of the Software, and to permit persons to whom the Software is"),
  BR_STRLC(" furnished to do so, subject to the following conditions:"),
  BR_STRLC(""),
  BR_STRLC(" The above copyright notice and this permission notice shall be included in"),
  BR_STRLC(" all copies or substantial portions of the Software."),
  BR_STRLC(""),
  BR_STRLC(" THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR"),
  BR_STRLC(" IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,"),
  BR_STRLC(" FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE"),
  BR_STRLC(" AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER"),
  BR_STRLC(" LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,"),
  BR_STRLC(" OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN"),
  BR_STRLC(" THE SOFTWARE."),
  BR_STRLC(""),
  BR_STRLC("===================================quick_benchmark============================"),
  BR_STRLC("===================================tests======================================"),
  BR_STRLC(" SPDX-License-Identifier: MIT"),
  BR_STRLC(" BR: Stolen from: https://github.com/yshui/test.h"),
  BR_STRLC("===================================tests======================================"),
  BR_STRLC("")
};
int br_license_lines = 363;

