const br_strv_t br_license[] = {
  BR_STRL("The MIT License (MIT)"),
  BR_STRL("Copyright © 2025 Branimir Ričko [branc116]"),
  BR_STRL(""),
  BR_STRL("Permission is hereby granted, free of charge, to any person  obtaining a copy of"),
  BR_STRL("this software and associated  documentation files (the   “Software”), to deal in"),
  BR_STRL("the Software without  restriction,  including without  limitation  the rights to"),
  BR_STRL("use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of"),
  BR_STRL("the Software,  and to permit persons to whom the Software is furnished to do so,"),
  BR_STRL("subject to the following conditions:"),
  BR_STRL(""),
  BR_STRL("The above  copyright notice and this  permission notice shall be included in all"),
  BR_STRL("copies or substantial portions of the Software."),
  BR_STRL(""),
  BR_STRL("THE SOFTWARE IS PROVIDED   “AS IS”,   WITHOUT WARRANTY OF ANY KIND,   EXPRESS OR"),
  BR_STRL("IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS"),
  BR_STRL("FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.   IN NO EVENT SHALL THE AUTHORS OR"),
  BR_STRL("COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,  DAMAGES OR OTHER LIABILITY,  WHETHER"),
  BR_STRL("IN  AN  ACTION  OF CONTRACT,   TORT OR OTHERWISE,   ARISING FROM,   OUT OF OR IN"),
  BR_STRL("CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE."),
  BR_STRL("==================================RAYLIB========================================"),
  BR_STRL("== Branimir =="),
  BR_STRL("Even tho I have removed raylib from this project. Some of the code is inspired by/copyed from"),
  BR_STRL("raylib. So if you find a line of code that Ramon created, it's thanks to him that this works."),
  BR_STRL("And if you find a line of code that Ramon created and it's because of that line that brplot doesn't work,"),
  BR_STRL("you should blame me."),
  BR_STRL("== End of Branimir =="),
  BR_STRL(" Copyright (c) 2013-2023 Ramon Santamaria (@raysan5)"),
  BR_STRL(""),
  BR_STRL(" This software is provided \"as-is\", without any express or implied warranty. In no event"),
  BR_STRL(" will the authors be held liable for any damages arising from the use of this software."),
  BR_STRL(""),
  BR_STRL(" Permission is granted to anyone to use this software for any purpose, including commercial"),
  BR_STRL(" applications, and to alter it and redistribute it freely, subject to the following restrictions:"),
  BR_STRL(""),
  BR_STRL("   1. The origin of this software must not be misrepresented; you must not claim that you"),
  BR_STRL("   wrote the original software. If you use this software in a product, an acknowledgment"),
  BR_STRL("   in the product documentation would be appreciated but is not required."),
  BR_STRL(""),
  BR_STRL("   2. Altered source versions must be plainly marked as such, and must not be misrepresented"),
  BR_STRL("   as being the original software."),
  BR_STRL(""),
  BR_STRL("   3. This notice may not be removed or altered from any source distribution."),
  BR_STRL("=================================RAYLIB========================================="),
  BR_STRL("=================================IMGUI=========================================="),
  BR_STRL("== Branimir =="),
  BR_STRL("Even tho I have removed imgui from this project. Some of the code is inspired by/copyed from"),
  BR_STRL("imgui. So if you find a line of code that Omar created, it's thanks to him that this works."),
  BR_STRL("And if you find a line of code that Omar created and it's because of that line that brplot doesn't work,"),
  BR_STRL("you should blame me."),
  BR_STRL("== End of Branimir =="),
  BR_STRL(" The MIT License (MIT)"),
  BR_STRL(""),
  BR_STRL(" Copyright (c) 2014-2024 Omar Cornut"),
  BR_STRL(""),
  BR_STRL(" Permission is hereby granted, free of charge, to any person obtaining a copy"),
  BR_STRL(" of this software and associated documentation files (the \"Software\"), to deal"),
  BR_STRL(" in the Software without restriction, including without limitation the rights"),
  BR_STRL(" to use, copy, modify, merge, publish, distribute, sublicense, and/or sell"),
  BR_STRL(" copies of the Software, and to permit persons to whom the Software is"),
  BR_STRL(" furnished to do so, subject to the following conditions:"),
  BR_STRL(""),
  BR_STRL(" The above copyright notice and this permission notice shall be included in all"),
  BR_STRL(" copies or substantial portions of the Software."),
  BR_STRL(""),
  BR_STRL(" THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR"),
  BR_STRL(" IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,"),
  BR_STRL(" FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE"),
  BR_STRL(" AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER"),
  BR_STRL(" LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,"),
  BR_STRL(" OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE"),
  BR_STRL(" SOFTWARE."),
  BR_STRL("=================================IMGUI=========================================="),
  BR_STRL("================================GLFW============================================"),
  BR_STRL(""),
  BR_STRL(" Copyright (c) 2002-2006 Marcus Geelnard"),
  BR_STRL(""),
  BR_STRL(" Copyright (c) 2006-2019 Camilla Löwy"),
  BR_STRL(""),
  BR_STRL(" This software is provided 'as-is', without any express or implied"),
  BR_STRL(" warranty. In no event will the authors be held liable for any damages"),
  BR_STRL(" arising from the use of this software."),
  BR_STRL(""),
  BR_STRL(" Permission is granted to anyone to use this software for any purpose,"),
  BR_STRL(" including commercial applications, and to alter it and redistribute it"),
  BR_STRL(" freely, subject to the following restrictions:"),
  BR_STRL(""),
  BR_STRL(" 1. The origin of this software must not be misrepresented; you must not"),
  BR_STRL("    claim that you wrote the original software. If you use this software"),
  BR_STRL("    in a product, an acknowledgment in the product documentation would"),
  BR_STRL("    be appreciated but is not required."),
  BR_STRL(""),
  BR_STRL(" 2. Altered source versions must be plainly marked as such, and must not"),
  BR_STRL("    be misrepresented as being the original software."),
  BR_STRL(""),
  BR_STRL(" 3. This notice may not be removed or altered from any source"),
  BR_STRL("    distribution."),
  BR_STRL(""),
  BR_STRL("===============================GLFW============================================="),
  BR_STRL("===============================TRACY============================================"),
  BR_STRL(""),
  BR_STRL(" Tracy Profiler (https://github.com/wolfpld/tracy) is licensed under the"),
  BR_STRL(" 3-clause BSD license."),
  BR_STRL(""),
  BR_STRL(" Copyright (c) 2017-2023, Bartosz Taudul <wolf@nereid.pl>"),
  BR_STRL(" All rights reserved."),
  BR_STRL(""),
  BR_STRL(" Redistribution and use in source and binary forms, with or without"),
  BR_STRL(" modification, are permitted provided that the following conditions are met:"),
  BR_STRL("     * Redistributions of source code must retain the above copyright"),
  BR_STRL("       notice, this list of conditions and the following disclaimer."),
  BR_STRL("     * Redistributions in binary form must reproduce the above copyright"),
  BR_STRL("       notice, this list of conditions and the following disclaimer in the"),
  BR_STRL("       documentation and/or other materials provided with the distribution."),
  BR_STRL("     * Neither the name of the <organization> nor the"),
  BR_STRL("       names of its contributors may be used to endorse or promote products"),
  BR_STRL("       derived from this software without specific prior written permission."),
  BR_STRL(""),
  BR_STRL(" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS \"AS IS\" AND"),
  BR_STRL(" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED"),
  BR_STRL(" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE"),
  BR_STRL(" DISCLAIMED. IN NO EVENT SHALL <COPYRIGHT HOLDER> BE LIABLE FOR ANY"),
  BR_STRL(" DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES"),
  BR_STRL(" (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;"),
  BR_STRL(" LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND"),
  BR_STRL(" ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT"),
  BR_STRL(" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS"),
  BR_STRL(" SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE."),
  BR_STRL("===============================TRACY==========================================="),
  BR_STRL("================================stb_image======================================"),
  BR_STRL(" ------------------------------------------------------------------------------"),
  BR_STRL(" This software is available under 2 licenses -- choose whichever you prefer."),
  BR_STRL(" ------------------------------------------------------------------------------"),
  BR_STRL(" ALTERNATIVE A - MIT License"),
  BR_STRL(" Copyright (c) 2017 Sean Barrett"),
  BR_STRL(" Permission is hereby granted, free of charge, to any person obtaining a copy of"),
  BR_STRL(" this software and associated documentation files (the \"Software\"), to deal in"),
  BR_STRL(" the Software without restriction, including without limitation the rights to"),
  BR_STRL(" use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies"),
  BR_STRL(" of the Software, and to permit persons to whom the Software is furnished to do"),
  BR_STRL(" so, subject to the following conditions:"),
  BR_STRL(" The above copyright notice and this permission notice shall be included in all"),
  BR_STRL(" copies or substantial portions of the Software."),
  BR_STRL(" THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR"),
  BR_STRL(" IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,"),
  BR_STRL(" FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE"),
  BR_STRL(" AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER"),
  BR_STRL(" LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,"),
  BR_STRL(" OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE"),
  BR_STRL(" SOFTWARE."),
  BR_STRL(" ------------------------------------------------------------------------------"),
  BR_STRL(" ALTERNATIVE B - Public Domain (www.unlicense.org)"),
  BR_STRL(" This is free and unencumbered software released into the public domain."),
  BR_STRL(" Anyone is free to copy, modify, publish, use, compile, sell, or distribute this"),
  BR_STRL(" software, either in source code form or as a compiled binary, for any purpose,"),
  BR_STRL(" commercial or non-commercial, and by any means."),
  BR_STRL(" In jurisdictions that recognize copyright laws, the author or authors of this"),
  BR_STRL(" software dedicate any and all copyright interest in the software to the public"),
  BR_STRL(" domain. We make this dedication for the benefit of the public at large and to"),
  BR_STRL(" the detriment of our heirs and successors. We intend this dedication to be an"),
  BR_STRL(" overt act of relinquishment in perpetuity of all present and future rights to"),
  BR_STRL(" this software under copyright law."),
  BR_STRL(" THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR"),
  BR_STRL(" IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,"),
  BR_STRL(" FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE"),
  BR_STRL(" AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN"),
  BR_STRL(" ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION"),
  BR_STRL(" WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE."),
  BR_STRL(" ------------------------------------------------------------------------------"),
  BR_STRL("================================stb_image======================================"),
  BR_STRL("================================stb_image_resize2=============================="),
  BR_STRL(" ------------------------------------------------------------------------------"),
  BR_STRL(" This software is available under 2 licenses -- choose whichever you prefer."),
  BR_STRL(" ------------------------------------------------------------------------------"),
  BR_STRL(" ALTERNATIVE A - MIT License"),
  BR_STRL(" Copyright (c) 2017 Sean Barrett"),
  BR_STRL(" Permission is hereby granted, free of charge, to any person obtaining a copy of"),
  BR_STRL(" this software and associated documentation files (the \"Software\"), to deal in"),
  BR_STRL(" the Software without restriction, including without limitation the rights to"),
  BR_STRL(" use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies"),
  BR_STRL(" of the Software, and to permit persons to whom the Software is furnished to do"),
  BR_STRL(" so, subject to the following conditions:"),
  BR_STRL(" The above copyright notice and this permission notice shall be included in all"),
  BR_STRL(" copies or substantial portions of the Software."),
  BR_STRL(" THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR"),
  BR_STRL(" IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,"),
  BR_STRL(" FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE"),
  BR_STRL(" AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER"),
  BR_STRL(" LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,"),
  BR_STRL(" OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE"),
  BR_STRL(" SOFTWARE."),
  BR_STRL(" ------------------------------------------------------------------------------"),
  BR_STRL(" ALTERNATIVE B - Public Domain (www.unlicense.org)"),
  BR_STRL(" This is free and unencumbered software released into the public domain."),
  BR_STRL(" Anyone is free to copy, modify, publish, use, compile, sell, or distribute this"),
  BR_STRL(" software, either in source code form or as a compiled binary, for any purpose,"),
  BR_STRL(" commercial or non-commercial, and by any means."),
  BR_STRL(" In jurisdictions that recognize copyright laws, the author or authors of this"),
  BR_STRL(" software dedicate any and all copyright interest in the software to the public"),
  BR_STRL(" domain. We make this dedication for the benefit of the public at large and to"),
  BR_STRL(" the detriment of our heirs and successors. We intend this dedication to be an"),
  BR_STRL(" overt act of relinquishment in perpetuity of all present and future rights to"),
  BR_STRL(" this software under copyright law."),
  BR_STRL(" THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR"),
  BR_STRL(" IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,"),
  BR_STRL(" FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE"),
  BR_STRL(" AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN"),
  BR_STRL(" ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION"),
  BR_STRL(" WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE."),
  BR_STRL(" ------------------------------------------------------------------------------"),
  BR_STRL("=================================stb_image_resize2============================="),
  BR_STRL("===================================stb_image_write============================="),
  BR_STRL(" ------------------------------------------------------------------------------"),
  BR_STRL(" This software is available under 2 licenses -- choose whichever you prefer."),
  BR_STRL(" ------------------------------------------------------------------------------"),
  BR_STRL(" ALTERNATIVE A - MIT License"),
  BR_STRL(" Copyright (c) 2017 Sean Barrett"),
  BR_STRL(" Permission is hereby granted, free of charge, to any person obtaining a copy of"),
  BR_STRL(" this software and associated documentation files (the \"Software\"), to deal in"),
  BR_STRL(" the Software without restriction, including without limitation the rights to"),
  BR_STRL(" use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies"),
  BR_STRL(" of the Software, and to permit persons to whom the Software is furnished to do"),
  BR_STRL(" so, subject to the following conditions:"),
  BR_STRL(" The above copyright notice and this permission notice shall be included in all"),
  BR_STRL(" copies or substantial portions of the Software."),
  BR_STRL(" THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR"),
  BR_STRL(" IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,"),
  BR_STRL(" FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE"),
  BR_STRL(" AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER"),
  BR_STRL(" LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,"),
  BR_STRL(" OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE"),
  BR_STRL(" SOFTWARE."),
  BR_STRL(" ------------------------------------------------------------------------------"),
  BR_STRL(" ALTERNATIVE B - Public Domain (www.unlicense.org)"),
  BR_STRL(" This is free and unencumbered software released into the public domain."),
  BR_STRL(" Anyone is free to copy, modify, publish, use, compile, sell, or distribute this"),
  BR_STRL(" software, either in source code form or as a compiled binary, for any purpose,"),
  BR_STRL(" commercial or non-commercial, and by any means."),
  BR_STRL(" In jurisdictions that recognize copyright laws, the author or authors of this"),
  BR_STRL(" software dedicate any and all copyright interest in the software to the public"),
  BR_STRL(" domain. We make this dedication for the benefit of the public at large and to"),
  BR_STRL(" the detriment of our heirs and successors. We intend this dedication to be an"),
  BR_STRL(" overt act of relinquishment in perpetuity of all present and future rights to"),
  BR_STRL(" this software under copyright law."),
  BR_STRL(" THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR"),
  BR_STRL(" IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,"),
  BR_STRL(" FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE"),
  BR_STRL(" AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN"),
  BR_STRL(" ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION"),
  BR_STRL(" WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE."),
  BR_STRL(" ------------------------------------------------------------------------------"),
  BR_STRL("===================================stb_image_write============================="),
  BR_STRL("===================================stb_rect_pack==============================="),
  BR_STRL(" ------------------------------------------------------------------------------"),
  BR_STRL(" This software is available under 2 licenses -- choose whichever you prefer."),
  BR_STRL(" ------------------------------------------------------------------------------"),
  BR_STRL(" ALTERNATIVE A - MIT License"),
  BR_STRL(" Copyright (c) 2017 Sean Barrett"),
  BR_STRL(" Permission is hereby granted, free of charge, to any person obtaining a copy of"),
  BR_STRL(" this software and associated documentation files (the \"Software\"), to deal in"),
  BR_STRL(" the Software without restriction, including without limitation the rights to"),
  BR_STRL(" use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies"),
  BR_STRL(" of the Software, and to permit persons to whom the Software is furnished to do"),
  BR_STRL(" so, subject to the following conditions:"),
  BR_STRL(" The above copyright notice and this permission notice shall be included in all"),
  BR_STRL(" copies or substantial portions of the Software."),
  BR_STRL(" THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR"),
  BR_STRL(" IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,"),
  BR_STRL(" FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE"),
  BR_STRL(" AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER"),
  BR_STRL(" LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,"),
  BR_STRL(" OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE"),
  BR_STRL(" SOFTWARE."),
  BR_STRL(" ------------------------------------------------------------------------------"),
  BR_STRL(" ALTERNATIVE B - Public Domain (www.unlicense.org)"),
  BR_STRL(" This is free and unencumbered software released into the public domain."),
  BR_STRL(" Anyone is free to copy, modify, publish, use, compile, sell, or distribute this"),
  BR_STRL(" software, either in source code form or as a compiled binary, for any purpose,"),
  BR_STRL(" commercial or non-commercial, and by any means."),
  BR_STRL(" In jurisdictions that recognize copyright laws, the author or authors of this"),
  BR_STRL(" software dedicate any and all copyright interest in the software to the public"),
  BR_STRL(" domain. We make this dedication for the benefit of the public at large and to"),
  BR_STRL(" the detriment of our heirs and successors. We intend this dedication to be an"),
  BR_STRL(" overt act of relinquishment in perpetuity of all present and future rights to"),
  BR_STRL(" this software under copyright law."),
  BR_STRL(" THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR"),
  BR_STRL(" IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,"),
  BR_STRL(" FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE"),
  BR_STRL(" AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN"),
  BR_STRL(" ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION"),
  BR_STRL(" WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE."),
  BR_STRL(" ------------------------------------------------------------------------------"),
  BR_STRL("===================================stb_rect_pack=============================="),
  BR_STRL("===================================stb_truetype==============================="),
  BR_STRL(" ------------------------------------------------------------------------------"),
  BR_STRL(" This software is available under 2 licenses -- choose whichever you prefer."),
  BR_STRL(" ------------------------------------------------------------------------------"),
  BR_STRL(" ALTERNATIVE A - MIT License"),
  BR_STRL(" Copyright (c) 2017 Sean Barrett"),
  BR_STRL(" Permission is hereby granted, free of charge, to any person obtaining a copy of"),
  BR_STRL(" this software and associated documentation files (the \"Software\"), to deal in"),
  BR_STRL(" the Software without restriction, including without limitation the rights to"),
  BR_STRL(" use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies"),
  BR_STRL(" of the Software, and to permit persons to whom the Software is furnished to do"),
  BR_STRL(" so, subject to the following conditions:"),
  BR_STRL(" The above copyright notice and this permission notice shall be included in all"),
  BR_STRL(" copies or substantial portions of the Software."),
  BR_STRL(" THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR"),
  BR_STRL(" IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,"),
  BR_STRL(" FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE"),
  BR_STRL(" AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER"),
  BR_STRL(" LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,"),
  BR_STRL(" OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE"),
  BR_STRL(" SOFTWARE."),
  BR_STRL(" ------------------------------------------------------------------------------"),
  BR_STRL(" ALTERNATIVE B - Public Domain (www.unlicense.org)"),
  BR_STRL(" This is free and unencumbered software released into the public domain."),
  BR_STRL(" Anyone is free to copy, modify, publish, use, compile, sell, or distribute this"),
  BR_STRL(" software, either in source code form or as a compiled binary, for any purpose,"),
  BR_STRL(" commercial or non-commercial, and by any means."),
  BR_STRL(" In jurisdictions that recognize copyright laws, the author or authors of this"),
  BR_STRL(" software dedicate any and all copyright interest in the software to the public"),
  BR_STRL(" domain. We make this dedication for the benefit of the public at large and to"),
  BR_STRL(" the detriment of our heirs and successors. We intend this dedication to be an"),
  BR_STRL(" overt act of relinquishment in perpetuity of all present and future rights to"),
  BR_STRL(" this software under copyright law."),
  BR_STRL(" THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR"),
  BR_STRL(" IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,"),
  BR_STRL(" FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE"),
  BR_STRL(" AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN"),
  BR_STRL(" ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION"),
  BR_STRL(" WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE."),
  BR_STRL(" ------------------------------------------------------------------------------"),
  BR_STRL("===================================stb_truetype================================"),
  BR_STRL("===================================stb_ds======================================"),
  BR_STRL(" ------------------------------------------------------------------------------"),
  BR_STRL(" This software is available under 2 licenses -- choose whichever you prefer."),
  BR_STRL(" ------------------------------------------------------------------------------"),
  BR_STRL(" ALTERNATIVE A - MIT License"),
  BR_STRL(" Copyright (c) 2019 Sean Barrett"),
  BR_STRL(" Permission is hereby granted, free of charge, to any person obtaining a copy of"),
  BR_STRL(" this software and associated documentation files (the \"Software\"), to deal in"),
  BR_STRL(" the Software without restriction, including without limitation the rights to"),
  BR_STRL(" use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies"),
  BR_STRL(" of the Software, and to permit persons to whom the Software is furnished to do"),
  BR_STRL(" so, subject to the following conditions:"),
  BR_STRL(" The above copyright notice and this permission notice shall be included in all"),
  BR_STRL(" copies or substantial portions of the Software."),
  BR_STRL(" THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR"),
  BR_STRL(" IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,"),
  BR_STRL(" FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE"),
  BR_STRL(" AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER"),
  BR_STRL(" LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,"),
  BR_STRL(" OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE"),
  BR_STRL(" SOFTWARE."),
  BR_STRL(" ------------------------------------------------------------------------------"),
  BR_STRL(" ALTERNATIVE B - Public Domain (www.unlicense.org)"),
  BR_STRL(" This is free and unencumbered software released into the public domain."),
  BR_STRL(" Anyone is free to copy, modify, publish, use, compile, sell, or distribute this"),
  BR_STRL(" software, either in source code form or as a compiled binary, for any purpose,"),
  BR_STRL(" commercial or non-commercial, and by any means."),
  BR_STRL(" In jurisdictions that recognize copyright laws, the author or authors of this"),
  BR_STRL(" software dedicate any and all copyright interest in the software to the public"),
  BR_STRL(" domain. We make this dedication for the benefit of the public at large and to"),
  BR_STRL(" the detriment of our heirs and successors. We intend this dedication to be an"),
  BR_STRL(" overt act of relinquishment in perpetuity of all present and future rights to"),
  BR_STRL(" this software under copyright law."),
  BR_STRL(" THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR"),
  BR_STRL(" IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,"),
  BR_STRL(" FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE"),
  BR_STRL(" AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN"),
  BR_STRL(" ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION"),
  BR_STRL(" WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE."),
  BR_STRL(" ------------------------------------------------------------------------------"),
  BR_STRL("===================================stb_ds======================================"),
  BR_STRL("===================================quick_benchmark============================="),
  BR_STRL(""),
  BR_STRL(" The MIT License"),
  BR_STRL(""),
  BR_STRL(" Copyright 2018 Andrea Vouk."),
  BR_STRL(""),
  BR_STRL(" Permission is hereby granted, free of charge, to any person obtaining a copy"),
  BR_STRL(" of this software and associated documentation files (the \"Software\"), to deal"),
  BR_STRL(" in the Software without restriction, including without limitation the rights"),
  BR_STRL(" to use, copy, modify, merge, publish, distribute, sublicense, and/or sell"),
  BR_STRL(" copies of the Software, and to permit persons to whom the Software is"),
  BR_STRL(" furnished to do so, subject to the following conditions:"),
  BR_STRL(""),
  BR_STRL(" The above copyright notice and this permission notice shall be included in"),
  BR_STRL(" all copies or substantial portions of the Software."),
  BR_STRL(""),
  BR_STRL(" THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR"),
  BR_STRL(" IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,"),
  BR_STRL(" FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE"),
  BR_STRL(" AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER"),
  BR_STRL(" LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,"),
  BR_STRL(" OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN"),
  BR_STRL(" THE SOFTWARE."),
  BR_STRL(""),
  BR_STRL("===================================quick_benchmark============================"),
  BR_STRL("===================================tests======================================"),
  BR_STRL(" SPDX-License-Identifier: MIT"),
  BR_STRL(" BR: Stolen from: https://github.com/yshui/test.h"),
  BR_STRL("===================================tests======================================"),
  BR_STRL("")
};
int br_license_lines = 404;

