#define _GNU_SOURCE
#include "include/brplot.h"
#include "external/shl_impls.c"
#include "src/platform.c"
#include "src/data.c"
#include "src/data_generator.c"
#include "src/filesystem.c"
#include "src/graph_utils.c"
#include "src/gui.c"
#include "src/keybindings.c"
#include "src/permastate.c"
#include "src/plot.c"
#include "src/plotter.c"
#include "src/q.c"
#include "src/read_input.c"
#include "src/shaders.c"
#include "src/mesh.c"
#include "src/icons.c"
#include "src/main.c"
#include "src/gl.c"
#include "src/text_renderer.c"
#include "src/resampling.c"
#include "src/theme.c"
#include "src/ui.c"
#include "src/threads.c"

// cc -I. -o brploto tools/unity/brplot.c -lm

